FROM centos:7
RUN rm -rf  /delete packer
yum install -y yum-utils && \
                    yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo && \
                    yum -y install terraform packer && \
                    yum install telnet elinks -y
                    